defaults: &defaults
  working_directory: ~/app/
  docker:
    - image: circleci/node:12
  resource_class: medium

version: 2.1
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=development yarn
      - run:
          nane: Lint
          command: yarn lint
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules/
  unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=development yarn
      - run: mkdir -p ./reports/jest/ ; true
      - run:
          name: Tests
          command: yarn test --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/jest/
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ./reports/jest/
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules/
  typescript:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=development yarn
      - run: yarn ts
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules/
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=development yarn
      - run: yarn build
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules/
  publish-dry-run:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=development yarn
      - run: yarn build
      - run: npm publish --dry-run
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules/

workflows:
  version: 2
  application:
    jobs:
      - unit-test
      - lint
      - typescript
      - build
      - publish-dry-run
